### ISSUE TITLE
Require cycle

### ISSUE THREAD

**Issue by mengerzhuanyong** [joltup/rn-fetch-blob#183]
Require cycle: node_modules/rn-fetch-blob/index.js -> node_modules/rn-fetch-blob/polyfill/index.js -> node_modules/rn-fetch-blob/polyfill/FileReader.js -> node_modules/rn-fetch-blob/index.js

It is recommended to solve this problem！

**Comment by reilem** [comment]
I'm also getting these warning on the new version of react-native.
```
Require cycle: node_modules/rn-fetch-blob/index.js -> node_modules/rn-fetch-blob/polyfill/index.js -> node_modules/rn-fetch-blob/polyfill/Blob.js -> node_modules/rn-fetch-blob/index.js
```

```
Require cycle: node_modules/rn-fetch-blob/index.js -> node_modules/rn-fetch-blob/polyfill/index.js -> node_modules/rn-fetch-blob/polyfill/XMLHttpRequest.js -> node_modules/rn-fetch-blob/index.js
```

```
Require cycle: node_modules/rn-fetch-blob/index.js -> node_modules/rn-fetch-blob/polyfill/index.js -> node_modules/rn-fetch-blob/polyfill/FileReader.js -> node_modules/rn-fetch-blob/index.js
```

```
Require cycle: node_modules/rn-fetch-blob/index.js -> node_modules/rn-fetch-blob/polyfill/index.js -> node_modules/rn-fetch-blob/polyfill/Fetch.js -> node_modules/rn-fetch-blob/index.js
```

**Comment by zhaiyjgithub** [comment]
same issue

**Comment by Bobozee** [comment]
same issue

**Comment by tenwiz** [comment]
Yes, I've faced the same issue here.

**Comment by tenwiz** [comment]
Require cycle: node_modules/rn-fetch-blob/index.js -> node_modules/rn-fetch-blob/polyfill/index.js -> node_modules/rn-fetch-blob/polyfill/Blob.js -> node_modules/rn-fetch-blob/index.js

**Comment by tskorupka** [comment]
Same issue :(

**Comment by nobady90** [comment]
Same same issue

**Comment by vaqif14** [comment]
same issue

**Comment by burtek** [comment]
same here

**Comment by RodrigoWP** [comment]
same here, any idea?

**Comment by AsadSaleh** [comment]
Any one already working on this issue? Or any one has an idea to solve this?

**Comment by wd** [comment]
@AsadSaleh This is not a critical problem, just a warning for 'maybe there is something wrong in your code', so you can simply ignore  this warning by add codes like bellow:

```
YellowBox.ignoreWarnings([
    'Remote debugger is in a background tab which may cause apps to perform slowly',
    'Require cycle: node_modules/rn-fetch-blob/index.js',
    'Require cycle: node_modules/react-native/Libraries/Network/fetch.js'
]);
```

**Comment by pakyo-pan** [comment]
any update on this ?

**Comment by soumyamishra89** [comment]
@wd This is a warning but needs to be dealt with. This has come up with new react-native version (0.57) and requires certain code restructuring in rn-fetch-blob library. 

Is anyone working on this?

**Comment by AGOGD** [comment]
I also encountered this problem today.

**Comment by zhuxianqin** [comment]
Modify these files can avoid require cycle:
IN DIR  rn-fetch-blob/polyfill
all thease 4 files:  Blob.js,  Fetch.js, FileReader.js, XMLHttpRequest.js

// import RNFetchBlob from '../index.js'
import {NativeModules} from 'react-native';
const RNFetchBlob = NativeModules.RNFetchBlob

**Comment by nhuthuynh195** [comment]
this problem has resolved, thanks brother
https://github.com/zhuxianqin

**Comment by Zbish** [comment]
there is going to be a PR for @zhuxianqin  fix ???

**Comment by zhuxianqin** [comment]
> @zhuxianqin can you please submit a PR with this fix?

sorry,  I don't know how to release github project, I will try to do it in several days

**Comment by zhuxianqin** [comment]
> @zhuxianqin can you please submit a PR with this fix?

to develop this project, I need to follow instructions below:
https://github.com/joltup/rn-fetch-blob-dev
I have to test both on android & IOS
Sorry, I think it's better for the original owner to fix it

**Comment by msqar** [comment]
@zhuxianqin seems that they are not adding it, it sucks man :( 

Seems that you know this library a lot, though. Can you help me with something? do you mind if i PM you?

**Comment by ThaJay** [comment]
This should be fixed. I'm glad react-native now warns about this but there should have never been cyclic dependencies in the first place.

The solution is also really easy, just make an interface with a setter and a getter and require the interface instead of the original class. The original file uses the setter and all others use the getter.

interface.js:
```javascript
let thing = {}

export function getThing () {
  return thing
}

export function setThing (thingToSet) {
  thing = thingToSet
}
```
thing.js:
```javascript
import {setThing} from './interface'

class Thing {}

setThing(Thing)
```
other files:
```javascript
import {getThing} from './interface'

const Thing = getThing()
```

**Comment by msqar** [comment]
@ThaJay yea man, i receive like 6-7 warning notifications every time i refresh the app, is getting super annoying. 
Do you have any idea how to apply this interface for this specific case?

**Comment by vitor-veras** [comment]
> Modify these files can avoid require cycle:
> IN DIR rn-fetch-blob/polyfill
> all thease 4 files: Blob.js, Fetch.js, FileReader.js, XMLHttpRequest.js
> 
> // import RNFetchBlob from '../index.js'
> import {NativeModules} from 'react-native';
> const RNFetchBlob = NativeModules.RNFetchBlob

This did the trick on RN 0.57
I think should be fixed...

**Comment by msqar** [comment]
@vitor-veras i have to put the fetch-blob file in my app and edit it then? no other way until they fix this? :/

**Comment by vitor-veras** [comment]
That's only a warning from React Native, but it can slowdown the app performance. And yes if you update the package with npm/yarn the fix will go away. There's no proper aproach to this i think, hopefully the dev team fix this soon.

**Comment by Faolain** [comment]
As mentioned by @alpha0010 in #296 one would encounter problems where RNFetchBlob is called within the files the import is removed from. 

@ThaJay would you be able to submit a PR?

**Comment by FibreFoX** [comment]
Just stupid me, but why are these polyfills even required here? As RN 0.59 comes with a new JavaScriptCore, are these polyfills still necessary? Or is there even a way to DISABLE these polyfills, like a non-polyfilled version of the lib?

**Comment by ThaJay** [comment]
I see. The next version of this could have these imports removed and only be compatible with 59 and up.
https://github.com/facebook/react-native/releases

**Comment by Bhavdip** [comment]
@zhuxianqin solution works perfectly.

**Comment by cristianoccazinsp** [comment]
Any updates? Seeing the same warnings

**Comment by mayconmesquita** [comment]
Any updates here?

**Comment by ithustle** [comment]
+1

**Comment by alpha0010** [comment]
Please test #357; I have insufficient time currently.

`npm install alpha0010/rn-fetch-blob#require-cycle`

**Comment by NoumanSakhawat** [comment]
> Modify these files can avoid require cycle:
> IN DIR rn-fetch-blob/polyfill
> all thease 4 files: Blob.js, Fetch.js, FileReader.js, XMLHttpRequest.js
> 
> // import RNFetchBlob from '../index.js'
> import {NativeModules} from 'react-native';
> const RNFetchBlob = NativeModules.RNFetchBlob

Thanks Buddy this is working

**Comment by tuanduc2904** [comment]
> Modify these files can avoid require cycle:
> IN DIR rn-fetch-blob/polyfill
> all thease 4 files: Blob.js, Fetch.js, FileReader.js, XMLHttpRequest.js
> 
> // import RNFetchBlob from '../index.js'
> import {NativeModules} from 'react-native';
> const RNFetchBlob = NativeModules.RNFetchBlob

I did the same thing, but I had problems calling the RNFetchBlob.config function.
This is my code
```
import {NativeModules} from 'react-native';
const { RNFetchBlob } = NativeModules;
RNFetchBlob.config(.....);
```
My code snippet shows an error:
`TypeError: undefined is not a function (near '...RNFetchBlob.RNFetchBlobConfig...')`

**Comment by Deg5112** [comment]
you can not just modify the node_module files i don't know why people are offering that as a solution

This needs to be fixed directly on this repo

**Comment by ThaJay** [comment]
@Deg5112 This is indeed one of the possible solutions to inject a dependency. I proposed another possibility but alas, no response thus far. I am not actively working with this at the moment but in a few weeks I might if nobody else has stepped in by then.

**Comment by CyrusZei** [comment]
any solution on this? or pr ?

**Comment by NoumanSakhawat** [comment]
> any solution on this? or pr ?

Here you go:



https://github.com/joltup/rn-fetch-blob/issues/183#issuecomment-450826541

**Comment by ThaJay** [comment]
@NoumanSakhawat That is not a solution, it's a workaround that has to be done after every node modules install. I guess the owner of this does not care because it has been 1,5 years by now.

**Comment by jessicarobins** [comment]
@ThaJay still a hack but you can use [patch-package](https://www.npmjs.com/package/patch-package) so at least you only have to modify it once and not after every npm install

**Comment by betoharres** [comment]
c'mom guys, what's wrong with this thread? the solutions was already posted here, let's submit a PR! let's move those lazy asses

**Comment by ThaJay** [comment]
@jessicarobins That looks like the first decently clean workaround I have come across.

**Comment by asasouza** [comment]
The problem continues on version 0.12.0, RN v 0.62.2

**Comment by osamaaamer95** [comment]
@asasouza install [patch-package](https://www.npmjs.com/package/patch-package), copy and paste this in a patch file named `rn-fetch-blob+0.12.0.patch` under `/patches`, reinstall node modules and run `patch-package`.

```diff
diff --git a/node_modules/rn-fetch-blob/polyfill/Blob.js b/node_modules/rn-fetch-blob/polyfill/Blob.js
index 53662a7..379a7ad 100644
--- a/node_modules/rn-fetch-blob/polyfill/Blob.js
+++ b/node_modules/rn-fetch-blob/polyfill/Blob.js
@@ -2,7 +2,9 @@
 // Use of this source code is governed by a MIT-style license that can be
 // found in the LICENSE file.
 
-import RNFetchBlob from '../index.js'
+// import RNFetchBlob from '../index.js'
+import {NativeModules} from 'react-native';
+const RNFetchBlob = NativeModules.RNFetchBlob
 import fs from '../fs.js'
 import getUUID from '../utils/uuid'
 import Log from '../utils/log.js'
diff --git a/node_modules/rn-fetch-blob/polyfill/Fetch.js b/node_modules/rn-fetch-blob/polyfill/Fetch.js
index 3ecb591..fbb0702 100644
--- a/node_modules/rn-fetch-blob/polyfill/Fetch.js
+++ b/node_modules/rn-fetch-blob/polyfill/Fetch.js
@@ -1,4 +1,6 @@
-import RNFetchBlob from '../index.js'
+// import RNFetchBlob from '../index.js'
+import {NativeModules} from 'react-native';
+const RNFetchBlob = NativeModules.RNFetchBlob
 import Log from '../utils/log.js'
 import fs from '../fs'
 import unicode from '../utils/unicode'
diff --git a/node_modules/rn-fetch-blob/polyfill/XMLHttpRequest.js b/node_modules/rn-fetch-blob/polyfill/XMLHttpRequest.js
index 9036b2b..f1a99e4 100644
--- a/node_modules/rn-fetch-blob/polyfill/XMLHttpRequest.js
+++ b/node_modules/rn-fetch-blob/polyfill/XMLHttpRequest.js
@@ -2,7 +2,9 @@
 // Use of this source code is governed by a MIT-style license that can be
 // found in the LICENSE file.
 
-import RNFetchBlob from '../index.js'
+// import RNFetchBlob from '../index.js'
+import {NativeModules} from 'react-native';
+const RNFetchBlob = NativeModules.RNFetchBlob
 import XMLHttpRequestEventTarget from './XMLHttpRequestEventTarget.js'
 import Log from '../utils/log.js'
 import Blob from './Blob.js'
```

**Comment by asasouza** [comment]
Thanks for the answer @osamaaamer95, after read the @jessicarobins comment this was my workaround too and worked.

**Comment by cmcleese** [comment]
Thank you @osamaaamer95 for this updated patch file.
From https://github.com/joltup/rn-fetch-blob/issues/183#issuecomment-621968820 .
This works for me.

**Comment by deltamish** [comment]
@osamaaamer95 did the exact same thing but still facing the issue 
D:/Work/Projects/VS/react-native-test/test-pdf-app/node_modules/rn-fetch-blob/index.js 12:12
Module parse failed: Unexpected token (12:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   AppState,
| } from 'react-native'
> import type {
|   RNFetchBlobNative,
|   RNFetchBlobConfig,

any idea why

**Comment by allan-simon** [comment]
@ihavenoface5 is it possible to have the patch included upstream ?

**Comment by ebarahona** [comment]
You can use your own forked repo.

> Modify these files can avoid require cycle:
> IN DIR rn-fetch-blob/polyfill
> all thease 4 files: Blob.js, Fetch.js, FileReader.js, XMLHttpRequest.js
> 
> // import RNFetchBlob from '../index.js'
> import {NativeModules} from 'react-native';
> const RNFetchBlob = NativeModules.RNFetchBlob

Fork the repo and apply the patch, install it from there until the fix is merged.  Change package.json to point to your fork.  Here is an example using a PUBLIC fork:

 "rn-fetch-blob": "git://github.com/foo/bar.git"

**Comment by allan-simon** [comment]
currently I use the patch-package solution , has this way, I will get updated if bug fixes are merged , without the hassle of maintaining our own fork

**Comment by ebarahona** [comment]
> currently I use the patch-package solution , has this way, I will get updated if bug fixes are merged , without the hassle of maintaining our own fork

Yep!  patch-package is definitely the best approach for bug fixes (like this).

**Comment by nicoladj77** [comment]
The patch-package approach doesn't work in Windows 10, I get an error in parsing the patch.

**Comment by darron1217** [comment]
Any update on this issue?
Is it complicated issue?

**Comment by ThaJay** [comment]
@darron1217 
On the one hand this repo is kinda dead.
On the other hand the owner does not want to break the latest version of this for (by now very) old versions of React Native.

It's very simple to solve by the way. If you con't care about supporting older versions of React-Native, justy remove some imports. If you want to keep the latest version working for everyone, properly solve the circle by some way of dependency injection.

I don't care at the moment because I'm not working on a project that uses this.
Read all the links in this topic if you're interested, all the information you would need is there.

**Comment by cristianoccazinsp** [comment]
I would love for the repo to not die.  It's so useful, even if the code is a bit hackish.

**Comment by Traviskn** [comment]
#666

**Comment by ilies-space** [comment]
> Modify these files can avoid require cycle:
> IN DIR rn-fetch-blob/polyfill
> all thease 4 files: Blob.js, Fetch.js, FileReader.js, XMLHttpRequest.js
> 
> // import RNFetchBlob from '../index.js'
> import {NativeModules} from 'react-native';
> const RNFetchBlob = NativeModules.RNFetchBlob

it's work thank you , but is it the best practice solution for this issue ?

**Comment by osamaaamer95** [comment]
You can fork the repo and do it that way too. However, I love `patch-package` because it is a simple solution that can be committed to your repository and work for other members of your team.

**Comment by ujangmisbah** [comment]
> Modify these files can avoid require cycle:
> IN DIR rn-fetch-blob/polyfill
> all thease 4 files: Blob.js, Fetch.js, FileReader.js, XMLHttpRequest.js
> 
> // import RNFetchBlob from '../index.js'
> import {NativeModules} from 'react-native';
> const RNFetchBlob = NativeModules.RNFetchBlob

Thanks this worked

**Comment by Rajan-Savaliya-spt** [comment]
import {NativeModules} from 'react-native';
const RNFetchBlob = NativeModules.RNFetchBlob

this solve this yellowbox ewarning but then libraray not working for me....

**Comment by MSH786** [comment]
> import {NativeModules} from 'react-native';
> const RNFetchBlob = NativeModules.RNFetchBlob

This also works in react-native-fetch-blob

Thanks Dude!

**Comment by storkyle** [comment]
> 
> 
> Modify these files can avoid require cycle:
> IN DIR rn-fetch-blob/polyfill
> all thease 4 files: Blob.js, Fetch.js, FileReader.js, XMLHttpRequest.js
> 
> // import RNFetchBlob from '../index.js'
> import {NativeModules} from 'react-native';
> const RNFetchBlob = NativeModules.RNFetchBlob

Thanks brother, @zhuxianqin !
--
Note: I made a patch from @zhuxianqin's solution. I hope that makes it easier 😃 

1.  install `patch-package`
2.  create a folder in your project called "patches"
3.  Inside "patches" folder get the patch from this gist (for convenience) https://gist.github.com/storkyle/d2f09ef376b3843915345150b0740977
4.  and name it as `rn-fetch-blob+0.12.0.patch `
5.  run `yarn install` or `npm install`

**Comment by Remigius2011** [comment]
@storkyle , thanks for the patch. this works for me.

Question: does anybody know of a maintained fork or a good replacement for rn-fetch-blob?

**Comment by cristianoccazinsp** [comment]
https://github.com/RonRadtke/react-native-blob-util

**Comment by alpha0010** [comment]
Self promotion: I wrote https://github.com/alpha0010/react-native-file-access when this library was marked as unmaintained.  API is similar, but implementation is completely new.  Feature set reduced to what I thought were the essentials (less code/simpler code means fewer places for bugs... in theory).

**Comment by dexiouz** [comment]
> Modify these files can avoid require cycle:
> IN DIR rn-fetch-blob/polyfill
> all thease 4 files: Blob.js, Fetch.js, FileReader.js, XMLHttpRequest.js
> 
> // import RNFetchBlob from '../index.js'
> import {NativeModules} from 'react-native';
> const RNFetchBlob = NativeModules.RNFetchBlob

Awesome. This fixed the issue for me

**Comment by keisan1231** [comment]
# I resolved this script

Please write in `${root}/script/rn-fetch-blob_warning.js`

```js
var fs = require('fs');

const replaced = `import RNFetchBlob from '../index.js'`;
const replacement = `import {NativeModules} from 'react-native';\nconst RNFetchBlob = NativeModules.RNFetchBlob`;

const files = [
  'node_modules/rn-fetch-blob/polyfill/Fetch.js',
  'node_modules/rn-fetch-blob/polyfill/Blob.js',
  'node_modules/rn-fetch-blob/polyfill/XMLHttpRequest.js',
];

files.forEach(file => {
  fs.readFile(file, 'utf8', function (err, data) {
    if (err) {
      return console.log(err);
    }

    var result = data.replace(new RegExp(replaced, 'g'), replacement);
    fs.writeFile(file, result, 'utf8', function (err) {
      if (err) return console.log(err);
    });
  });
});
```


and in `package.json`

```json
"scripts": {
.....
    "postinstall": "node scripts/rn-fetch-blob_warning.js"
  },
```

Please reinstall. (`yarn install`)
Then , waring vanishes

**Comment by gtaylor44** [comment]
Thank you @storkyle ... Don't need to manually patch each time packages are installed with this solution.

**Comment by Faseeh-Abbas-Khan** [comment]
> Modify these files can avoid require cycle: IN DIR rn-fetch-blob/polyfill all thease 4 files: Blob.js, Fetch.js, FileReader.js, XMLHttpRequest.js
> 
> // import RNFetchBlob from '../index.js' import {NativeModules} from 'react-native'; const RNFetchBlob = NativeModules.RNFetchBlob

Worked for me

**Comment by satyabrata45** [comment]
Same issue

**Comment by rk-maker** [comment]
> Modify these files can avoid require cycle: IN DIR rn-fetch-blob/polyfill all thease 4 files: Blob.js, Fetch.js, FileReader.js, XMLHttpRequest.js
> 
> // import RNFetchBlob from '../index.js' import {NativeModules} from 'react-native'; const RNFetchBlob = NativeModules.RNFetchBlob

Thanks man this issue has been resolved

**Comment by biplovappservinc** [comment]
> 

this is all are fixing not a permanent solution.

**Comment by technokasim** [comment]
> Modify these files can avoid require cycle: IN DIR rn-fetch-blob/polyfill all thease 4 files: Blob.js, Fetch.js, FileReader.js, XMLHttpRequest.js
> 
> // import RNFetchBlob from '../index.js' import {NativeModules} from 'react-native'; const RNFetchBlob = NativeModules.RNFetchBlob

It works for me. thanks

**Comment by pond** [comment]
Cyclic dependencies for almost 4 years and still not fixed?

That's... Unfortunate `:-O`

**Comment by lfrallon** [comment]
Hello, this still exists on:

"react": "18.0.0",
"react-native": "^0.69.0",
"rn-fetch-blob": "^0.12.0",

Update: 

Fix after I installed `"rn-fetch-blob": "0.13.0-beta.2"` mentioned in https://github.com/joltup/rn-fetch-blob/issues/798#issuecomment-1218917753.

**Comment by mickey35vn** [comment]
> it works for me, many thanks

**Comment by mickey35vn** [comment]
> Modify these files can avoid require cycle: IN DIR rn-fetch-blob/polyfill all thease 4 files: Blob.js, Fetch.js, FileReader.js, XMLHttpRequest.js
> 
> // import RNFetchBlob from '../index.js' import {NativeModules} from 'react-native'; const RNFetchBlob = NativeModules.RNFetchBlob

it works for me, many thanks

**Comment by Adil7767** [comment]
Require cycle: node_modules/rn-fetch-blob/index.js -> node_modules/rn-fetch-blob/polyfill/index.js -> node_modules/rn-fetch-blob/polyfill/Fetch.js -> node_modules/rn-fetch-blob/index.js Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
same issue is here
